// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_base.proto

package com.zfoo.net.packet.protobuf;

public final class MessageBase {
  private MessageBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionModuleType);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionModuleIndex);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionMessageId);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionCmdName);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionXmlFile);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionXmlOnly);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionXmlMessageAlias);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionServerOnly);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionFieldAlias);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionIpv4Field);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionDateTimeField);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionHint);
    registry.add(com.zfoo.net.packet.protobuf.MessageBase.optionXmlValueAlias);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int OPTIONMODULETYPE_FIELD_NUMBER = 2000;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      com.zfoo.net.packet.protobuf.MessageIdDefine.EModuleIndex> optionModuleType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.zfoo.net.packet.protobuf.MessageIdDefine.EModuleIndex.class,
        null);
  public static final int OPTIONMODULEINDEX_FIELD_NUMBER = 2001;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      java.lang.Integer> optionModuleIndex = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int OPTIONMESSAGEID_FIELD_NUMBER = 2000;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      com.zfoo.net.packet.protobuf.MessageIdDefine.EMessageId> optionMessageId = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.zfoo.net.packet.protobuf.MessageIdDefine.EMessageId.class,
        null);
  public static final int OPTIONCMDNAME_FIELD_NUMBER = 2001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> optionCmdName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONXMLFILE_FIELD_NUMBER = 3000;
  /**
   * <pre>
   * XML文件名
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> optionXmlFile = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONXMLONLY_FIELD_NUMBER = 3001;
  /**
   * <pre>
   * 只使用XML格式，不打包
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> optionXmlOnly = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int OPTIONXMLMESSAGEALIAS_FIELD_NUMBER = 3002;
  /**
   * <pre>
   * 消息别名
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> optionXmlMessageAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONSERVERONLY_FIELD_NUMBER = 3000;
  /**
   * <pre>
   * 是否只在服务端使用
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> optionServerOnly = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int OPTIONFIELDALIAS_FIELD_NUMBER = 3001;
  /**
   * <pre>
   * 消息节点别名
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> optionFieldAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONIPV4FIELD_FIELD_NUMBER = 3002;
  /**
   * <pre>
   * IPV4字段
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> optionIpv4Field = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int OPTIONDATETIMEFIELD_FIELD_NUMBER = 3003;
  /**
   * <pre>
   * 日期时间字段
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> optionDateTimeField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int OPTIONHINT_FIELD_NUMBER = 3000;
  /**
   * <pre>
   *注释
   * </pre>
   *
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> optionHint = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int OPTIONXMLVALUEALIAS_FIELD_NUMBER = 3001;
  /**
   * <pre>
   *字段值的别名
   * </pre>
   *
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> optionXmlValueAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022message_base.proto\022\002CK\032 google/protobu" +
      "f/descriptor.proto\032\027message_id_define.pr" +
      "oto:I\n\020OptionModuleType\022\034.google.protobu" +
      "f.EnumOptions\030\320\017 \001(\0162\020.CK.EModuleIndex:8" +
      "\n\021OptionModuleIndex\022\034.google.protobuf.En" +
      "umOptions\030\321\017 \001(\r:I\n\017OptionMessageId\022\037.go" +
      "ogle.protobuf.MessageOptions\030\320\017 \001(\0162\016.CK" +
      ".EMessageId:7\n\rOptionCmdName\022\037.google.pr" +
      "otobuf.MessageOptions\030\321\017 \001(\t:7\n\rOptionXm" +
      "lFile\022\037.google.protobuf.MessageOptions\030\270" +
      "\027 \001(\t:7\n\rOptionXmlOnly\022\037.google.protobuf" +
      ".MessageOptions\030\271\027 \001(\010:?\n\025OptionXmlMessa" +
      "geAlias\022\037.google.protobuf.MessageOptions" +
      "\030\272\027 \001(\t:8\n\020OptionServerOnly\022\035.google.pro" +
      "tobuf.FieldOptions\030\270\027 \001(\010:8\n\020OptionField" +
      "Alias\022\035.google.protobuf.FieldOptions\030\271\027 " +
      "\001(\t:7\n\017OptionIpv4Field\022\035.google.protobuf" +
      ".FieldOptions\030\272\027 \001(\010:;\n\023OptionDateTimeFi" +
      "eld\022\035.google.protobuf.FieldOptions\030\273\027 \001(" +
      "\010:6\n\nOptionHint\022!.google.protobuf.EnumVa" +
      "lueOptions\030\270\027 \001(\t:?\n\023OptionXmlValueAlias" +
      "\022!.google.protobuf.EnumValueOptions\030\271\027 \001" +
      "(\tB \n\034com.zfoo.net.packet.protobufH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.zfoo.net.packet.protobuf.MessageIdDefine.getDescriptor(),
        });
    optionModuleType.internalInit(descriptor.getExtensions().get(0));
    optionModuleIndex.internalInit(descriptor.getExtensions().get(1));
    optionMessageId.internalInit(descriptor.getExtensions().get(2));
    optionCmdName.internalInit(descriptor.getExtensions().get(3));
    optionXmlFile.internalInit(descriptor.getExtensions().get(4));
    optionXmlOnly.internalInit(descriptor.getExtensions().get(5));
    optionXmlMessageAlias.internalInit(descriptor.getExtensions().get(6));
    optionServerOnly.internalInit(descriptor.getExtensions().get(7));
    optionFieldAlias.internalInit(descriptor.getExtensions().get(8));
    optionIpv4Field.internalInit(descriptor.getExtensions().get(9));
    optionDateTimeField.internalInit(descriptor.getExtensions().get(10));
    optionHint.internalInit(descriptor.getExtensions().get(11));
    optionXmlValueAlias.internalInit(descriptor.getExtensions().get(12));
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.zfoo.net.packet.protobuf.MessageIdDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
