// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_money_common.proto

package com.zfoo.net.packet.protobuf;

public final class MsgMoneyCommon {
  private MsgMoneyCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBPriceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CK.PBPriceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *货币类型
     * </pre>
     *
     * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
     * @return Whether the moneyType field is set.
     */
    boolean hasMoneyType();
    /**
     * <pre>
     *货币类型
     * </pre>
     *
     * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
     * @return The moneyType.
     */
    com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType getMoneyType();

    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>optional int32 price = 2;</code>
     * @return Whether the price field is set.
     */
    boolean hasPrice();
    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>optional int32 price = 2;</code>
     * @return The price.
     */
    int getPrice();
  }
  /**
   * <pre>
   * 统一使用的货币类型
   * </pre>
   *
   * Protobuf type {@code CK.PBPriceInfo}
   */
  public static final class PBPriceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CK.PBPriceInfo)
      PBPriceInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PBPriceInfo.newBuilder() to construct.
    private PBPriceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBPriceInfo() {
      moneyType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PBPriceInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBPriceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType value = com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                moneyType_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              price_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zfoo.net.packet.protobuf.MsgMoneyCommon.internal_static_CK_PBPriceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zfoo.net.packet.protobuf.MsgMoneyCommon.internal_static_CK_PBPriceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.class, com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.Builder.class);
    }

    private int bitField0_;
    public static final int MONEY_TYPE_FIELD_NUMBER = 1;
    private int moneyType_;
    /**
     * <pre>
     *货币类型
     * </pre>
     *
     * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
     * @return Whether the moneyType field is set.
     */
    @java.lang.Override public boolean hasMoneyType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *货币类型
     * </pre>
     *
     * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
     * @return The moneyType.
     */
    @java.lang.Override public com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType getMoneyType() {
      @SuppressWarnings("deprecation")
      com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType result = com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType.valueOf(moneyType_);
      return result == null ? com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType.Item_None : result;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;
    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>optional int32 price = 2;</code>
     * @return Whether the price field is set.
     */
    @java.lang.Override
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>optional int32 price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public int getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, moneyType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, moneyType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo)) {
        return super.equals(obj);
      }
      com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo other = (com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo) obj;

      if (hasMoneyType() != other.hasMoneyType()) return false;
      if (hasMoneyType()) {
        if (moneyType_ != other.moneyType_) return false;
      }
      if (hasPrice() != other.hasPrice()) return false;
      if (hasPrice()) {
        if (getPrice()
            != other.getPrice()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMoneyType()) {
        hash = (37 * hash) + MONEY_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + moneyType_;
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getPrice();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 统一使用的货币类型
     * </pre>
     *
     * Protobuf type {@code CK.PBPriceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CK.PBPriceInfo)
        com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zfoo.net.packet.protobuf.MsgMoneyCommon.internal_static_CK_PBPriceInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zfoo.net.packet.protobuf.MsgMoneyCommon.internal_static_CK_PBPriceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.class, com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.Builder.class);
      }

      // Construct using com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        moneyType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zfoo.net.packet.protobuf.MsgMoneyCommon.internal_static_CK_PBPriceInfo_descriptor;
      }

      @java.lang.Override
      public com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo getDefaultInstanceForType() {
        return com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo build() {
        com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo buildPartial() {
        com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo result = new com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.moneyType_ = moneyType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.price_ = price_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo) {
          return mergeFrom((com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo other) {
        if (other == com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo.getDefaultInstance()) return this;
        if (other.hasMoneyType()) {
          setMoneyType(other.getMoneyType());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int moneyType_ = 0;
      /**
       * <pre>
       *货币类型
       * </pre>
       *
       * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
       * @return Whether the moneyType field is set.
       */
      @java.lang.Override public boolean hasMoneyType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *货币类型
       * </pre>
       *
       * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
       * @return The moneyType.
       */
      @java.lang.Override
      public com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType getMoneyType() {
        @SuppressWarnings("deprecation")
        com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType result = com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType.valueOf(moneyType_);
        return result == null ? com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType.Item_None : result;
      }
      /**
       * <pre>
       *货币类型
       * </pre>
       *
       * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
       * @param value The moneyType to set.
       * @return This builder for chaining.
       */
      public Builder setMoneyType(com.zfoo.net.packet.protobuf.MsgGameTypes.EItemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        moneyType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *货币类型
       * </pre>
       *
       * <code>optional .CK.EItemType money_type = 1 [default = Item_None];</code>
       * @return This builder for chaining.
       */
      public Builder clearMoneyType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        moneyType_ = 0;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>optional int32 price = 2;</code>
       * @return Whether the price field is set.
       */
      @java.lang.Override
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>optional int32 price = 2;</code>
       * @return The price.
       */
      @java.lang.Override
      public int getPrice() {
        return price_;
      }
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>optional int32 price = 2;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>optional int32 price = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CK.PBPriceInfo)
    }

    // @@protoc_insertion_point(class_scope:CK.PBPriceInfo)
    private static final com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo();
    }

    public static com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBPriceInfo>
        PARSER = new com.google.protobuf.AbstractParser<PBPriceInfo>() {
      @java.lang.Override
      public PBPriceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBPriceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBPriceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBPriceInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zfoo.net.packet.protobuf.MsgMoneyCommon.PBPriceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CK_PBPriceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CK_PBPriceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026msg_money_common.proto\022\002CK\032\024msg_game_t" +
      "ypes.proto\"J\n\013PBPriceInfo\022,\n\nmoney_type\030" +
      "\001 \001(\0162\r.CK.EItemType:\tItem_None\022\r\n\005price" +
      "\030\002 \001(\005B \n\034com.zfoo.net.packet.protobufH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zfoo.net.packet.protobuf.MsgGameTypes.getDescriptor(),
        });
    internal_static_CK_PBPriceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CK_PBPriceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CK_PBPriceInfo_descriptor,
        new java.lang.String[] { "MoneyType", "Price", });
    com.zfoo.net.packet.protobuf.MsgGameTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
